void quitMenu();
void generateAccountNumber(char *str, size_t size);
bool validateAdmin(char* id, char* pass);
bool login();
int signinscreen();
bool createAccount();
bool findAccountNumber(char *acc_no, float* balance, char* dets);
bool withdrawMoney();
void depositMoney();
void displayUsers();
int displayMenu();
bool connectToServer();
void alarm_handler();
